### ISSUE TITLE
Error on build RHEL 6/7

### ISSUE THREAD

**Issue by lgnap** [iusrepo/drone-rpmbuild#1]
I'm trying to add `rpmlint` package (you'll see a PR in few minutes) to all `Dockerfile`.
And In doing that I tested all builds and rhel 6/7 don't work anymore.
It's not related to `rpmlint` addition (tried without)

```
Step 9/12 : RUN echo 'drone ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/drone
 ---> Running in c101a4cad2c0
/bin/sh: /etc/sudoers.d/drone: No such file or directory
```
Seems that a not well installed sudo package ?

**Comment by carlwgeorge** [comment]
Sorry, I don't use drone anymore since they switched to a proprietary license in 1.0.  I'd link you to discussions about it but the maintainer had a habit of deleting them.  I'll archive this repo to make the status clear.  Feel free to clone the commits and do whatever you like with them in your own namespace.
